//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;
using System.ComponentModel;

namespace EntityManager
{
    /// <summary>
    /// 实体类DiningUSER。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("DiningUSER")]
    [Serializable]
    public partial class DiningUSER : Entity
    {
        #region Model
		private int? _ID;
		private string _USER;
		private string _NAME;
		private string _PWD;
		private string _GROUP;
		private int? _VIPLevel;
		private long? _ISADMIN;
		private string _ISENABLE;
		private string _CREATEUSER;
		private DateTime? _CREATEDATE;
		private string _MODIFYUSER;
		private DateTime? _MODIFYDATE;
		private DateTime _ROWVERSION;

		/// <summary>
		/// 
		/// </summary>
		[Field("ID")]
		public int? ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("USER")]
        [DisplayName("帐户")]
		public string USER
		{
			get{ return _USER; }
			set
			{
				this.OnPropertyValueChange("USER");
				this._USER = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("NAME")]
        [DisplayName("用户名称")]
        public string NAME
		{
			get{ return _NAME; }
			set
			{
				this.OnPropertyValueChange("NAME");
				this._NAME = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("PWD")]
		public string PWD
		{
			get{ return _PWD; }
			set
			{
				this.OnPropertyValueChange("PWD");
				this._PWD = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("GROUP")]
		public string GROUP
		{
			get{ return _GROUP; }
			set
			{
				this.OnPropertyValueChange("GROUP");
				this._GROUP = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("VIPLevel")]
        [DisplayName("等级")]
		public int? VIPLevel
		{
			get{ return _VIPLevel; }
			set
			{
				this.OnPropertyValueChange("VIPLevel");
				this._VIPLevel = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ISADMIN")]
		public long? ISADMIN
		{
			get{ return _ISADMIN; }
			set
			{
				this.OnPropertyValueChange("ISADMIN");
				this._ISADMIN = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ISENABLE")]
        [DisplayName("是否有效")]
		public string ISENABLE
		{
			get{ return _ISENABLE; }
			set
			{
				this.OnPropertyValueChange("ISENABLE");
				this._ISENABLE = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CREATEUSER")]
		public string CREATEUSER
		{
			get{ return _CREATEUSER; }
			set
			{
				this.OnPropertyValueChange("CREATEUSER");
				this._CREATEUSER = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CREATEDATE")]
        [DisplayName("创建时间")]
        public DateTime? CREATEDATE
		{
			get{ return _CREATEDATE; }
			set
			{
				this.OnPropertyValueChange("CREATEDATE");
				this._CREATEDATE = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("MODIFYUSER")]
		public string MODIFYUSER
		{
			get{ return _MODIFYUSER; }
			set
			{
				this.OnPropertyValueChange("MODIFYUSER");
				this._MODIFYUSER = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("MODIFYDATE")]
		public DateTime? MODIFYDATE
		{
			get{ return _MODIFYDATE; }
			set
			{
				this.OnPropertyValueChange("MODIFYDATE");
				this._MODIFYDATE = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ROWVERSION")]
		public DateTime ROWVERSION
		{
			get{ return _ROWVERSION; }
			set
			{
				this.OnPropertyValueChange("ROWVERSION");
				this._ROWVERSION = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.USER,
				_.NAME,
				_.PWD,
				_.GROUP,
				_.VIPLevel,
				_.ISADMIN,
				_.ISENABLE,
				_.CREATEUSER,
				_.CREATEDATE,
				_.MODIFYUSER,
				_.MODIFYDATE,
				_.ROWVERSION,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._USER,
				this._NAME,
				this._PWD,
				this._GROUP,
				this._VIPLevel,
				this._ISADMIN,
				this._ISENABLE,
				this._CREATEUSER,
				this._CREATEDATE,
				this._MODIFYUSER,
				this._MODIFYDATE,
				this._ROWVERSION,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "DiningUSER");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "DiningUSER", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field USER = new Field("USER", "DiningUSER", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field NAME = new Field("NAME", "DiningUSER", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PWD = new Field("PWD", "DiningUSER", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field GROUP = new Field("GROUP", "DiningUSER", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field VIPLevel = new Field("VIPLevel", "DiningUSER", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ISADMIN = new Field("ISADMIN", "DiningUSER", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ISENABLE = new Field("ISENABLE", "DiningUSER", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CREATEUSER = new Field("CREATEUSER", "DiningUSER", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CREATEDATE = new Field("CREATEDATE", "DiningUSER", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MODIFYUSER = new Field("MODIFYUSER", "DiningUSER", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MODIFYDATE = new Field("MODIFYDATE", "DiningUSER", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ROWVERSION = new Field("ROWVERSION", "DiningUSER", "");
        }
        #endregion
	}
}