//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;
using System.ComponentModel;

namespace EntityManager
{
    /// <summary>
    /// 实体类DiningCookingType。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("DiningCookingType")]
    [Serializable]
    public partial class DiningCookingType : Entity
    {
        #region Model
		private int? _ID;
		private string _CookingType;
		private string _CREATEUSER;
		private DateTime? _CREATEDATE;
		private string _MODIFYUSER;
		private DateTime? _MODIFYDATE;
		private DateTime _ROWVERSION;

		/// <summary>
		/// 
		/// </summary>
		[Field("ID")]
		public int? ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange("ID");
				this._ID = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CookingType")]
        [DisplayName("菜类类型")]
		public string CookingType
		{
			get{ return _CookingType; }
			set
			{
				this.OnPropertyValueChange("CookingType");
				this._CookingType = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CREATEUSER")]
        [DisplayName("创建人")]
        public string CREATEUSER
		{
			get{ return _CREATEUSER; }
			set
			{
				this.OnPropertyValueChange("CREATEUSER");
				this._CREATEUSER = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("CREATEDATE")]
        [DisplayName("创建时间")]
        public DateTime? CREATEDATE
		{
			get{ return _CREATEDATE; }
			set
			{
				this.OnPropertyValueChange("CREATEDATE");
				this._CREATEDATE = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("MODIFYUSER")]
		public string MODIFYUSER
		{
			get{ return _MODIFYUSER; }
			set
			{
				this.OnPropertyValueChange("MODIFYUSER");
				this._MODIFYUSER = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("MODIFYDATE")]
		public DateTime? MODIFYDATE
		{
			get{ return _MODIFYDATE; }
			set
			{
				this.OnPropertyValueChange("MODIFYDATE");
				this._MODIFYDATE = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("ROWVERSION")]
		public DateTime ROWVERSION
		{
			get{ return _ROWVERSION; }
			set
			{
				this.OnPropertyValueChange("ROWVERSION");
				this._ROWVERSION = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.ID,
				_.CookingType,
				_.CREATEUSER,
				_.CREATEDATE,
				_.MODIFYUSER,
				_.MODIFYDATE,
				_.ROWVERSION,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._ID,
				this._CookingType,
				this._CREATEUSER,
				this._CREATEDATE,
				this._MODIFYUSER,
				this._MODIFYDATE,
				this._ROWVERSION,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "DiningCookingType");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "DiningCookingType", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CookingType = new Field("CookingType", "DiningCookingType", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CREATEUSER = new Field("CREATEUSER", "DiningCookingType", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CREATEDATE = new Field("CREATEDATE", "DiningCookingType", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MODIFYUSER = new Field("MODIFYUSER", "DiningCookingType", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MODIFYDATE = new Field("MODIFYDATE", "DiningCookingType", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ROWVERSION = new Field("ROWVERSION", "DiningCookingType", "");
        }
        #endregion
	}
}